name: AKS WordPress Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  RESOURCE_GROUP: Devops-POC-Akshay
  AKS_CLUSTER: wordpress-learning-aks
  HELM_RELEASE: wordpress
  NAMESPACE: default

jobs:

  deploy:
    runs-on: self-hosted

    steps:

    # Checkout repo
    - name: Checkout
      uses: actions/checkout@v4

    # Azure Login
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Get AKS Credentials
    - name: Get AKS Credentials
      run: |
        az aks get-credentials \
          --resource-group $RESOURCE_GROUP \
          --name $AKS_CLUSTER \
          --overwrite-existing

    # Add Helm repo
    - name: Add Helm Repo
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo update

    # Helm Upgrade (MAIN DEPLOYMENT STEP)
    - name: Helm Upgrade WordPress
      run: |
        helm upgrade --install $HELM_RELEASE bitnami/wordpress \
          --namespace $NAMESPACE \
          --set global.security.allowInsecureImages=true \
          --set wordpressBlogName="DevOps Blog" \
          --set service.type=LoadBalancer

    # Verify rollout
    - name: Check Pods
      run: |
        kubectl get pods -n $NAMESPACE
        kubectl rollout status deployment/$HELM_RELEASE
