name: AKS WordPress Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  RESOURCE_GROUP: Devops-POC-Akshay
  AKS_CLUSTER: wordpress-learning-aks
  HELM_RELEASE: wordpress
  NAMESPACE: default

jobs:

  # =========================
  # 1. DEPLOY
  # =========================
  deploy:
    runs-on: self-hosted

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Get AKS Credentials
      run: |
        az aks get-credentials \
          --resource-group $RESOURCE_GROUP \
          --name $AKS_CLUSTER \
          --overwrite-existing

    - name: Add Helm Repo
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo update

    - name: Helm Deploy
      run: |
        helm upgrade --install $HELM_RELEASE bitnami/wordpress \
          --namespace $NAMESPACE \
          --set image.tag=invalid-tag-xyz-123 \
          --set global.security.allowInsecureImages=true \
          --set service.type=LoadBalancer

    - name: Verify Deployment
      run: |
        kubectl rollout status deployment/$HELM_RELEASE -n $NAMESPACE


  # =========================
  # 2. FAILURE CHECK 
  # =========================
  detect-failure:
    needs: deploy
    if: failure()
    runs-on: self-hosted

    steps:
      - name: Deployment Failed
        run: echo "Deployment failed — waiting for approval for rollback"


  # =========================
  # 3. MANUAL APPROVAL
  # =========================
  approve-rollback:
    needs: detect-failure
    runs-on: self-hosted
    environment:
      name: rollback-approval  

    steps:
      - name: Wait for human approval
        run: echo "Rollback approved"


  # =========================
  # 4. ROLLBACK
  # =========================
  rollback:
    needs: approve-rollback
    runs-on: self-hosted

    steps:

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Get AKS Credentials
      run: |
        az aks get-credentials \
          --resource-group $RESOURCE_GROUP \
          --name $AKS_CLUSTER \
          --overwrite-existing

    - name: Rollback WordPress
      run: |
        helm rollback $HELM_RELEASE -n $NAMESPACE
